### ISSUE TITLE
Pentaho 9.0.0 - saml kar loaded in karaf

### ISSUE THREAD

**Issue by jbouzekri** [pentaho/pentaho-engineering-samples#105]
We tried to follow the doc (which is for Pentaho 6.0) in Pentaho 9.0. The Pentaho 9.0 archive installation is working okay. However when we put the kar in pentaho-solutions/system/karaf/deploy, we get this error : 

```
13:00:19,268 ERROR [BlueprintContainerImpl] Unable to start container for blueprint bundle pentaho-saml/9.1.0.0-SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:741)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:433)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:298)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:311)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:280)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:276)
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:266)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)
	at org.apache.felix.framework.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:730)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:485)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/pentaho/platform/proxy/impl/ProxyException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at org.apache.aries.blueprint.utils.generics.TypeInference.findConstructors(TypeInference.java:180)
	at org.apache.aries.blueprint.utils.generics.TypeInference.findMatchingConstructors(TypeInference.java:124)
	at org.apache.aries.blueprint.container.BeanRecipe.findMatchingConstructors(BeanRecipe.java:373)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstanceFromType(BeanRecipe.java:346)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:283)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:685)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:666)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:90)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:360)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:190)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:737)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.proxy.impl.ProxyException not found by pentaho-saml [270]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
```

But the pentaho-proxy-factory jar is in the tomcat WEB-INF lib folder and seems to be loaded.

**Comment by jbouzekri** [comment]
I needed to set the correct Pentaho version in pom.xml when building the kar : 

https://github.com/pentaho/pentaho-engineering-samples/blob/master/Samples_for_Extending_Pentaho/Reference%20Implementations/Security/SAML%202.0/pom.xml

```
  <parent>
    <groupId>org.pentaho</groupId>
    <artifactId>pentaho-ce-jar-parent-pom</artifactId>
    <version>9.0.0.0-423</version>
  </parent>

  <groupId>pentaho</groupId>
  <artifactId>pentaho-authentication-provider-samples</artifactId>
  <version>9.0.0.0-423</version>
  <packaging>pom</packaging>
```
