### ISSUE TITLE
NullPointerException while instantiating samlAuthenticationManager

### ISSUE THREAD

**Issue by jpiazza** [pentaho/pentaho-engineering-samples#34]
Hi!

Following the documentation: https://help.pentaho.com/Documentation/6.1/0P0/150/010/Set_Up_SAML_for_BA_Server

We found out the following exception:
```
27-Oct-2017 11:46:39.853 INFO [Thread-18] org.pentaho.caching.impl.PentahoCacheManagerFactory$RegistrationHandler$1.onSuccess New Caching Service registered
11:46:40,512 ERROR [BlueprintContainerImpl] Unable to start blueprint container for bundle pentaho-saml
org.osgi.service.blueprint.container.ComponentDefinitionException: Error when instantiating bean samlAuthenticationManager of class org.pentaho.platform.spring.security.saml.PentahoAuthen$
        at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:333)
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:806)
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
        at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
Caused by: java.lang.ClassCastException: org.springframework.security.providers.ProviderManager cannot be cast to org.springframework.security.authentication.AuthenticationManager
        at org.pentaho.platform.spring.security.saml.PentahoAuthenticationManagerDelegate.<init>(PentahoAuthenticationManagerDelegate.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.aries.blueprint.utils.ReflectionUtils.newInstance(ReflectionUtils.java:329)
        at org.apache.aries.blueprint.container.BeanRecipe.newInstance(BeanRecipe.java:962)
        at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:331)
        ... 42 more
```

Further reading on the code showed us that 
```
        IProxyFactory factory = PentahoSystem.get( IProxyFactory.class );
```

Is returning null.

Why would it be?

Is there any extraparameter we are missing?

Thank you very much and kind regards,
Jose

**Comment by pedrofvteixeira** [comment]
Hey @jpiazza , just tried it on my end ( linking it to my okta SAML account ), and all seems well. To help pinpoint the cause for the issue you're experiencing, can you please provide me with the following information?

- As you're following the https://help.pentaho.com/Documentation/6.1/0P0/150/010/Set_Up_SAML_for_BA_Server , this means you are using a `BA-Server 6.1.0.x`, correct ?
- If you're using a `BA-Server 6.1.0.x` to set up SAML, which git branch are you building it from? 
  Should not be from `master`, but from `6.1` branch
- Did you drop the required`applicationContext-spring-security-saml.xml` in `<install-dir>/pentaho-solutions/system` ?
  - and updated` pentaho-spring-beans.xml` to include this new `(..)-saml.xml` ?

Best regards,

Pedro T.

**Comment by jpiazza** [comment]
Thanks for your quik response.1- Yes, I'm using Ba-Server 6.1 on JDK8 2- Yes, I build form branch 6.13- Yes, I did frop the (..)-saml.xml file and updated pentaho-spring-beans.xml file.
Can't understand what is causing the problem.
Again, thanks por your response.

    El lunes, 30 de octubre de 2017 09:53:53 ART, Pedro Teixeira <notifications@github.com> escribió:  
 
 
Hey @jpiazza , just tried it on my end ( linking it to my okta SAML account ), and all seems well. To help pinpoint the cause for the issue you're experiencing, can you please provide me with the following information?
   
   - As you're following the https://help.pentaho.com/Documentation/6.1/0P0/150/010/Set_Up_SAML_for_BA_Server , this means you are using a BA-Server 6.1.0.x, correct ?
   - If you're using a BA-Server 6.1.0.x to set up SAML, which git branch are you building it from?   
Should not be from master, but from 6.1 branch
   - Did you drop the requiredapplicationContext-spring-security-saml.xml in <install-dir>/pentaho-solutions/system ?      
      - and updatedpentaho-spring-beans.xml to include this new (..)-saml.xml ?


Best regards,

Pedro T.

**Comment by pedrofvteixeira** [comment]
Hi @jpiazza , 

- what is the value set for `provider`, at `pentaho-solutions/system/security.properties` ?
- can you please paste here the full contents of your `pentaho-solutions/system/karaf/etc/custom.properties` ?


Best regards,

Pedro T.

**Comment by pedrofvteixeira** [comment]
Hi @jpiazza ,

have you been able to get the Pentaho-SAML-sample up-&-running ?

Best regards,

Pedro T.

**Comment by jpiazza** [comment]
Sorry I didnit response your email. I'm  with other task right now.I'll reasume the Pentaho issue in some days.

Best regards,

José

    El lunes, 6 de noviembre de 2017 12:52:50 ART, Pedro Teixeira <notifications@github.com> escribió:  
 
 
Hi @jpiazza ,

have you been able to get the Pentaho-SAML-sample up-&-running ?

Best regards,

Pedro T.

**Comment by asabolansky** [comment]
Hi!

I have the same problem. The value at pentaho-solutions/system/security.properties is saml.

Regards
Alejandro
